# fly.toml app configuration file generated for html2pdf-service on 2025-05-30T09:09:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'html2pdf-service'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 5007
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
